// export const phrasesTheLastOfUs = [
//   { phrase: "You have no idea what loss is.", translation: "Ти навіть не уявляєш, що таке втрата." },
//   { phrase: "We don’t have to do this. You know that, right?", translation: "Нам не обов’язково це робити. Ти ж це знаєш, правда?" },
//   { phrase: "No matter what, you keep finding something to fight for.", translation: "Незалежно від усього, ти завжди знаходиш за що боротися." },
//   { phrase: "I struggled for a long time with survivin’. And you… No matter what, you keep going.", translation: "Я довго боровся, щоби вижити. А ти… Незалежно від усього, ти йдеш далі." },
//   { phrase: "You don’t get to rush this.", translation: "Не треба поспішати." },
//   { phrase: "It ain't for you to decide.", translation: "Це не тобі вирішувати." },
//   { phrase: "It's not time to be a hero.", translation: "Зараз не час бути героєм." },
//   { phrase: "You have to trust me.", translation: "Ти мусиш мені довіряти." },
//   { phrase: "I ain't leavin’ without you.", translation: "Я без тебе не піду." },
//   { phrase: "I got you, baby girl.", translation: "Я тримаю тебе, малятко." },
//   { phrase: "After all we’ve been through. Everything that I’ve done. It can’t be for nothing.", translation: "Після всього, що ми пережили. Після всього, що я зробила. Це не може бути марно." },
//   { phrase: "Everyone I have cared for has either died or left me. Everyone… except for you.", translation: "Усі, про кого я піклувалася, або загинули, або покинули мене. Усі… окрім тебе." },
//   { phrase: "Well, that’s stupid.", translation: "Ну, це дурість." },
//   { phrase: "You're not my dad. And I'm sure as hell not your daughter.", translation: "Ти мені не тато. І я вже точно не твоя дочка." },
//   { phrase: "You just hang back like a good little boy and watch from a distance.", translation: "Просто стій осторонь, як хороший хлопчик, і спостерігай здалеку." },
//   { phrase: "This is not okay, Joel!", translation: "Це не нормально, Джоеле!" },
//   { phrase: "I guess we're both disappointed in each other then.", translation: "Думаю, ми обидва розчаровані одне в одному." },
//   { phrase: "I know you mean well, but there’s no halfway with this.", translation: "Я знаю, що ти бажаєш добра, але тут немає напівзаходів." },
//   { phrase: "We fight for every second we get to spend with each other.", translation: "Ми боремося за кожну секунду, яку можемо провести разом." },
//   { phrase: "I don’t wanna end up like my mom.", translation: "Я не хочу закінчити, як моя мама." },
//   { phrase: "We’re shitty people, Joel. It’s been that way for a long time.", translation: "Ми паршиві люди, Джоеле. І так було вже давно." },
//   { phrase: "There’s enough here that you have to feel some sort of obligation to me.", translation: "Тут достатньо причин, щоб ти відчував хоча б якусь відповідальність переді мною." },
//   { phrase: "Guess what? We’re shitty people. It’s been that way for a long time.", translation: "Знаєш що? Ми погані люди. І так було завжди." },
//   { phrase: "There’s no halfway with this.", translation: "Тут немає півзаходів." },
//   { phrase: "Joel, I can handle this.", translation: "Джоеле, я впораюся." },
//   { phrase: "You know, as bad as those things are, at least they’re predictable.", translation: "Знаєш, якими б жахливими вони не були, принаймні вони передбачувані." },
//   { phrase: "If we’re gonna do this, we’re gonna do this my way.", translation: "Якщо ми це зробимо, то за моїми правилами." },
//   { phrase: "Let’s just get on with it.", translation: "Давай просто зробимо це." },
//   { phrase: "Joel, don’t waste this gift.", translation: "Джоеле, не марнуй цей шанс." },
//   { phrase: "I need you to get her to Tommy’s.", translation: "Мені потрібно, щоб ти відвів її до Томмі." },
//   { phrase: "I have a family, Joel. I don’t do that anymore.", translation: "У мене є сім'я, Джоеле. Я більше цим не займаюся." },
//   { phrase: "We ain’t back in Boston, Joel.", translation: "Ми вже не в Бостоні, Джоеле." },
//   { phrase: "You have no idea what it cost me.", translation: "Ти не уявляєш, чого мені це коштувало." },
//   { phrase: "Maria and I are grateful for what you’ve done.", translation: "Марія і я вдячні за те, що ти зробив." },
//   { phrase: "I’m not gonna do this again, Joel.", translation: "Я не збираюся це повторювати, Джоеле." },
//   { phrase: "Just because life stopped for you doesn’t mean it has to stop for me.", translation: "Тільки тому, що твоє життя зупинилося, не означає, що моє теж повинно." },
//   { phrase: "If anything, anything at all happens to her, it’s on you.", translation: "Якщо з нею щось станеться, хоч що-небудь – це твоя вина." },
//   { phrase: "You survived because of me!", translation: "Ти вижив завдяки мені!" },
//   { phrase: "The hell we do.", translation: "Та фіг там!" },
//   { phrase: "Don’t bring your bullshit into my home.", translation: "Не принось свій непотріб у мій дім." },
//   { phrase: "You’re capable of more than you think.", translation: "Ти здатний на більше, ніж думаєш." },
//   { phrase: "If you knew what was good for you, you’d turn around and leave.", translation: "Якби ти знав, що для тебе добре, ти б просто пішов." },
//   { phrase: "He’s my husband, and I trust him.", translation: "Це мій чоловік, і я йому довіряю." },
//   { phrase: "You have to stop living in the past.", translation: "Ти мусиш перестати жити минулим." },
//   { phrase: "We all make sacrifices.", translation: "Ми всі йдемо на жертви." },
//   { phrase: "Don’t make me regret this.", translation: "Не змушуй мене про це шкодувати." },
//   { phrase: "You’re one tough kid.", translation: "Ти міцна дівчина." },
//   { phrase: "You’re lucky to have him.", translation: "Тобі пощастило мати його поруч." },
//   { phrase: "I’ve seen people like you before.", translation: "Я вже бачила таких, як ти." },
//   { phrase: "Not everyone gets a second chance.", translation: "Не всім дається другий шанс." }
// ];

export const phrasesTNoPunIntended = [
  { phrase: "It doesn't matter how much you push the envelope. It’ll still be stationary.", translation: "Немає значення, наскільки ви натискаєте на конверт. Він все ще буде нерухомим." },
  { phrase: "What did the Confederate soldiers use to eat off of? Civil ware.", translation: "Що їли солдати Конфедерації? Цивільний посуд." },
  { phrase: "I walked into my sister's room and tripped on a bra. It was a booby-trap.", translation: "Я зайшла в кімнату сестри й спіткнулася об бюстгальтер. Це була міна-пастка." },
  { phrase: "A book just fell on my head. I only have my shelf to blame.", translation: "Мені просто на голову впала книга. Мені звинувачувати лише свою полицю." },
  { phrase: "What is the leading cause of divorce in long-term marriages? A stale-mate.", translation: "Що є основною причиною розлучень у довготривалих шлюбах? Затій партнер." },
  { phrase: "A moon rock tastes better than an earthly rock because it's meteor.", translation: "Місячний камінь на смак кращий, ніж земний, тому що це метеор." },
  { phrase: "A backwards poet writes inverse.", translation: "Задом наперед поет пише інверсію." },
  { phrase: "I used to be addicted to soap. But I'm clean now.", translation: "Раніше я був залежний від мила. Але тепер я чистий." },
  { phrase: "I stayed up all night wondering where the sun went. Then it dawned on me.", translation: "Я не спав всю ніч, гадаючи, куди поділося сонце. Тоді мене осяяло." },
  { phrase: "What did the mermaid wear to her math class? An algae bra.", translation: "У що була одягнена русалка на урок математики? Бюстгальтер з водоростями." },
  { phrase: "Why did the scarecrow get a promotion? He was outstanding in his field.", translation: "Чому опудало отримало підвищення? Він був видатним у своїй галузі." },
  { phrase: "I tried to catch some fog earlier. I mist.", translation: "Раніше намагався зловити туман. я туман." },
  { phrase: "You know what's not right? Left.", translation: "Знаєш, що не так? Ліворуч." },
  { phrase: "What does a pirate say while eating sushi? Ahoy! Pass me some soy!", translation: "Що говорить пірат, коли їсть суші? привіт! Дайте мені трохи сої!" },
  { phrase: "You wanna hear a joke about pizza? Never mind, it was too cheesy.", translation: "Хочеш почути анекдот про піцу? Нічого, це було надто сирно." },
  { phrase: "What did the green grape say to the purple grape? Breathe, you idiot!", translation: "Що сказав зелений виноград фіолетовому? Дихай, ідіот!" },
  { phrase: "What did the cannibal get when he showed up to the party late? A cold shoulder!", translation: "Що отримав канібал, коли запізнився на вечірку? Холодне плече!" },
  { phrase: "I'm reading a book about anti-gravity. It's impossible to put down.", translation: "Я читаю книгу про антигравітацію. Неможливо відірватися." },
  { phrase: "I'm glad I know sign language. It's become quite handy.", translation: "Я забув, як кинути бумеранг. Але це повернулося до мене." },
  { phrase: "When a clock is hungry... It goes back four seconds.", translation: "Коли годинник голодний... Він повертається на чотири секунди назад." },
  { phrase: "I once heard a joke about amnesia... But I forget how it goes.", translation: "Колись чув анекдот про амнезію... Але я забув, як це буває." },
  { phrase: "When the power went out at the school... The children... were de-lighted.", translation: "Коли в школі зникла електрика... Діти... були в захваті." },
  { phrase: "The frustrated cannibal threw up his hands.", translation: "Розчарований канібал розвів руками." },
  { phrase: "I didn't have the faintest idea... as to why I passed out.", translation: "Я не мав жодного уявлення... чому я втратив свідомість." },
  { phrase: "There was once a crossed-eyed teacher... who had issues controlling his pupils.", translation: "Був колись косоокий вчитель... якому було важко контролювати своїх учнів." },
  { phrase: "I heard two peanuts walk into a park... One was as-salted.", translation: "Я чув, як два арахіси йшли в парк... Один був солоний." },
  { phrase: "Cartoonist found dead at home, details are sketchy.", translation: "Карикатуриста знайшли мертвим удома, деталі уривчасті." },
  { phrase: "The Magician got frustrated and pulled his hare out.", translation: "Чарівник розчарувався і витягнув свого зайця." },
  { phrase: "A criminal's best asset... is his lie-ability.", translation: "Найкраще надбання злочинця... це його здатність брехати." },
  { phrase: "I heard about the guy who got hit in the head with a can of soda. He is lucky it was a soft drink.", translation: "Я чув про хлопця, якого вдарили по голові банкою газованої води. Йому пощастило, що це був безалкогольний напій." },
  { phrase: "He told the chef his steak was undercooked, so the chef said it was a rare mistake", translation: "Він сказав шеф-кухарю, що його стейк недосмажений, тому шеф сказав, що це була рідкісна помилка." },
  { phrase: "I used to play piano by ear, but now I use my hands.", translation: "Раніше я грав на фортепіано на слух, а тепер – руками." },
  { phrase: "I couldn't figure out how lightning works, but then it struck me.", translation: "Я не міг зрозуміти, як працює блискавка, але потім вона вразила мене." },
  { phrase: "Why did the math book look sad? Because it had too many problems.", translation: "Чому зошит з математики виглядав сумно? Тому що було надто багато проблем." },
  { phrase: "I told my wife she was drawing her eyebrows too high. She looked surprised.", translation: "Я сказав своїй дружині, що вона малює свої брови занадто високо. Вона виглядала здивованою." },
];